[build]
  publish = "."
  command = ""

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=86400, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=86400, immutable"
