/* F6 夜晚点窗观星：古星图数据（三垣 · 二十八宿）
 * 坐标 x,y ∈ [0,1]，绘制时映射到星图内容区（左→右 / 上→下）。
 * 视角：地面仰望 —— 北(玄武)在顶、南(朱雀)在底、东(青龙)在左、西(白虎)在右。
 * 二十八宿每宿由多颗星连成星官轮廓；主星(id 同旧)保留讲解，辅助星仅用于连线。
 * 中宫（三垣·紫微/太微/天市/勾陈/帝，及北斗七星）亦带讲解，与二十八宿同入「介绍池」。
 * 每宿含 descYanming（阎明）/ descLiqingning（清凝）两套讲解。
 */
window.YLT_CFG = window.YLT_CFG || {};
window.YLT_CFG.stars = [
  { id: "dou", name: "斗宿", group: "玄武", x: 0.19, y: 0.12, descYanming: "斗宿为北方玄武第一宿，是北方玄武的蛇头和蛇身，又称斗木獬。其主星官“斗”由六颗星构成斗勺状，称南斗六星。道教有“南斗注生，北斗注死”之说。", descLiqingning: "“维南有箕，不可以簸扬；维北有斗，不可以挹酒浆。”" },
  { id: "dou1", name: "", group: "玄武", x: 0.22, y: 0.1 },
  { id: "dou2", name: "", group: "玄武", x: 0.25, y: 0.09 },
  { id: "dou3", name: "", group: "玄武", x: 0.28, y: 0.1 },
  { id: "dou4", name: "", group: "玄武", x: 0.31, y: 0.12 },
  { id: "dou5", name: "", group: "玄武", x: 0.33, y: 0.14 },
  { id: "niu", name: "牛宿", group: "玄武", x: 0.29, y: 0.08, descYanming: "牛宿因其星群排列形似牛角得名，别名牵牛。", descLiqingning: "古人常把斗宿和牛宿连起来称为“斗牛”。" },
  { id: "niu1", name: "", group: "玄武", x: 0.31, y: 0.07 },
  { id: "niu2", name: "", group: "玄武", x: 0.33, y: 0.08 },
  { id: "niu3", name: "", group: "玄武", x: 0.34, y: 0.1 },
  { id: "nv", name: "女宿", group: "玄武", x: 0.39, y: 0.1, descYanming: "女宿也叫“女”、“须女”、“婺女”，别称女土蝠。其星群组合形似簸箕或“女”字。", descLiqingning: "《礼记·月令》中记载了立夏时节的星象：“孟夏之月，日在毕，昏翼中，旦婺女中。”" },
  { id: "nv1", name: "", group: "玄武", x: 0.41, y: 0.08 },
  { id: "nv2", name: "", group: "玄武", x: 0.42, y: 0.11 },
  { id: "nv3", name: "", group: "玄武", x: 0.43, y: 0.09 },
  { id: "xu", name: "虚宿", group: "玄武", x: 0.49, y: 0.08, descYanming: "虚宿又名“天节”，也称玄枵、虚日鼠。", descLiqingning: "《左传·昭公四年》：“古者日在北陆而藏冰”，北陆指‌虚宿‌，时令对应‌深冬。" },
  { id: "xu1", name: "", group: "玄武", x: 0.52, y: 0.1 },
  { id: "wei2", name: "危宿", group: "玄武", x: 0.59, y: 0.09, descYanming: "危宿别称危月燕，居玄武尾部。", descLiqingning: "《晋书·天文志》：“危三星，主天府市架屋。”" },
  { id: "wei21", name: "", group: "玄武", x: 0.62, y: 0.08 },
  { id: "wei22", name: "", group: "玄武", x: 0.64, y: 0.11 },
  { id: "shi", name: "室宿", group: "玄武", x: 0.69, y: 0.11, descYanming: "室宿，室火猪，别称营星、定星，又名清庙、玄宫，因处玄武七宿正中间，亦有象征天子宫殿之说。", descLiqingning: "室宿原与壁宿合称营室，《诗经》“定之方中，作于楚宫。”，是农闲筑屋的标志。" },
  { id: "shi1", name: "", group: "玄武", x: 0.72, y: 0.13 },
  { id: "bi", name: "壁宿", group: "玄武", x: 0.79, y: 0.09, descYanming: "壁宿主星官由两颗星组成，别名东壁或壁水貐。", descLiqingning: "古人把壁宿看作天上的书库，唐代张说有诗云“东壁图书府，西园翰墨林”。" },
  { id: "bi1", name: "", group: "玄武", x: 0.82, y: 0.11 },
  { id: "jiao", name: "角宿", group: "青龙", x: 0.11, y: 0.17, descYanming: "角宿是东方青龙七宿第一宿，是中国古代星空中恒星坐标的起点，别名角木蛟。左角主法理，右角主将领。", descLiqingning: "角宿又称“天门”或“天关”“屈原《天问》中有“角宿未旦，曜灵安藏？”" },
  { id: "jiao1", name: "", group: "青龙", x: 0.14, y: 0.2 },
  { id: "kang", name: "亢宿", group: "青龙", x: 0.12, y: 0.24, descYanming: "亢又称亢金龙，“亢”本义为人颈，因其位置拟为东方青龙之颈。", descLiqingning: "亢金龙在《西游记》中有出场~" },
  { id: "kang1", name: "", group: "青龙", x: 0.13, y: 0.27 },
  { id: "kang2", name: "", group: "青龙", x: 0.12, y: 0.3 },
  { id: "kang3", name: "", group: "青龙", x: 0.13, y: 0.33 },
  { id: "di", name: "氐宿", group: "青龙", x: 0.1, y: 0.37, descYanming: "在角宿和心宿中间的位置，有一个四颗星组成的“勺斗”，即为氐宿，又称氐土貉。", descLiqingning: "《史记》载“氐者言万物皆至也”。" },
  { id: "di1", name: "", group: "青龙", x: 0.14, y: 0.38 },
  { id: "di2", name: "", group: "青龙", x: 0.14, y: 0.42 },
  { id: "di3", name: "", group: "青龙", x: 0.1, y: 0.43 },
  { id: "fang", name: "房宿", group: "青龙", x: 0.1, y: 0.47, descYanming: "房宿，又称房日兔，古称“天驷”，指四颗主星形似天马。", descLiqingning: "《尔雅·释天》：“天驷，房也。”注称：“龙为天马，故房四星谓之天驷。”" },
  { id: "fang1", name: "", group: "青龙", x: 0.13, y: 0.47 },
  { id: "fang2", name: "", group: "青龙", x: 0.16, y: 0.47 },
  { id: "fang3", name: "", group: "青龙", x: 0.18, y: 0.47 },
  { id: "xin", name: "心宿", group: "青龙", x: 0.13, y: 0.57, descYanming: "心宿，又称明堂、心月狐、商宿、商星。在《镜花缘》中，心月狐受命下凡，化身女皇武则天。", descLiqingning: "“七月流火，九月授衣。”“火”即心宿二，古称“大火”。" },
  { id: "xin1", name: "", group: "青龙", x: 0.1, y: 0.55 },
  { id: "xin2", name: "", group: "青龙", x: 0.16, y: 0.59 },
  { id: "wei", name: "尾宿", group: "青龙", x: 0.11, y: 0.66, descYanming: "尾宿九星弯如钩，是苍龙摆动的尾。古以尾为后宫，亦主君臣。", descLiqingning: "“丙之晨，龙尾伏辰。”" },
  { id: "wei1", name: "", group: "青龙", x: 0.13, y: 0.69 },
  { id: "wei2", name: "", group: "青龙", x: 0.15, y: 0.72 },
  { id: "wei3", name: "", group: "青龙", x: 0.16, y: 0.75 },
  { id: "wei4", name: "", group: "青龙", x: 0.17, y: 0.78 },
  { id: "wei5", name: "", group: "青龙", x: 0.16, y: 0.81 },
  { id: "wei6", name: "", group: "青龙", x: 0.14, y: 0.83 },
  { id: "ji", name: "箕宿", group: "青龙", x: 0.11, y: 0.86, descYanming: "箕宿主风，又称箕星好风。晒药最怕它起，转眼一场雨。", descLiqingning: "箕宿像一只簸箕，风一吹，就把云都扬散了。" },
  { id: "ji1", name: "", group: "青龙", x: 0.14, y: 0.85 },
  { id: "ji2", name: "", group: "青龙", x: 0.15, y: 0.88 },
  { id: "ji3", name: "", group: "青龙", x: 0.12, y: 0.89 },
  { id: "kui", name: "奎宿", group: "白虎", x: 0.85, y: 0.17, descYanming: "奎宿主沟渎、武库，亦主封豕。足踏之地，水流自成。", descLiqingning: "奎宿散散的，像白虎踩过的雪地脚印。" },
  { id: "kui1", name: "", group: "白虎", x: 0.88, y: 0.16 },
  { id: "kui2", name: "", group: "白虎", x: 0.9, y: 0.18 },
  { id: "kui3", name: "", group: "白虎", x: 0.87, y: 0.2 },
  { id: "kui4", name: "", group: "白虎", x: 0.89, y: 0.21 },
  { id: "lou", name: "娄宿", group: "白虎", x: 0.86, y: 0.27, descYanming: "娄宿主畜牧牺牲，亦主聚众。牧马放羊，望它而知时。", descLiqingning: "娄宿圆圆的，像草场上刚堆好的草垛。" },
  { id: "lou1", name: "", group: "白虎", x: 0.88, y: 0.26 },
  { id: "lou2", name: "", group: "白虎", x: 0.87, y: 0.29 },
  { id: "wei3", name: "胃宿", group: "白虎", x: 0.88, y: 0.37, descYanming: "胃宿号天仓，主五谷积聚。秋收满仓，便拜此宿。", descLiqingning: "胃宿鼓鼓的，像一只装满了的布袋。" },
  { id: "wei31", name: "", group: "白虎", x: 0.9, y: 0.36 },
  { id: "wei32", name: "", group: "白虎", x: 0.87, y: 0.39 },
  { id: "mao", name: "昴宿", group: "白虎", x: 0.85, y: 0.49, descYanming: "昴宿七星聚如髦头，西方称七姊妹。主狱事，亦主边兵。", descLiqingning: "昴宿挤挤挨挨，像七个姐妹凑着说悄悄话。" },
  { id: "mao1", name: "", group: "白虎", x: 0.86, y: 0.48 },
  { id: "mao2", name: "", group: "白虎", x: 0.87, y: 0.49 },
  { id: "mao3", name: "", group: "白虎", x: 0.86, y: 0.5 },
  { id: "mao4", name: "", group: "白虎", x: 0.88, y: 0.49 },
  { id: "mao5", name: "", group: "白虎", x: 0.87, y: 0.51 },
  { id: "bi2", name: "毕宿", group: "白虎", x: 0.88, y: 0.6, descYanming: "毕宿主弋猎，形如捕兔之网，又名毕好雨，网张则雨至。", descLiqingning: "毕宿张开像一张网，专门兜住要落下的雨。" },
  { id: "bi21", name: "", group: "白虎", x: 0.85, y: 0.61 },
  { id: "bi22", name: "", group: "白虎", x: 0.83, y: 0.63 },
  { id: "bi23", name: "", group: "白虎", x: 0.86, y: 0.64 },
  { id: "bi24", name: "", group: "白虎", x: 0.89, y: 0.63 },
  { id: "zi", name: "觜宿", group: "白虎", x: 0.85, y: 0.71, descYanming: "觜为虎嘴，主三军粮草、葆旅之事。小小三星，管的是口中食。", descLiqingning: "觜宿尖尖的，像白虎抿着嘴，不肯出声。" },
  { id: "zi1", name: "", group: "白虎", x: 0.87, y: 0.7 },
  { id: "zi2", name: "", group: "白虎", x: 0.86, y: 0.73 },
  { id: "shen", name: "参宿", group: "白虎", x: 0.85, y: 0.8, descYanming: "参宿为白虎之身，主斩伐威武。它与心宿（商）永不相见，谓参商。", descLiqingning: "“人生不相见，动如参与商。”" },
  { id: "shen1", name: "", group: "白虎", x: 0.89, y: 0.8 },
  { id: "shen2", name: "", group: "白虎", x: 0.89, y: 0.85 },
  { id: "shen3", name: "", group: "白虎", x: 0.85, y: 0.85 },
  { id: "shen4", name: "", group: "白虎", x: 0.86, y: 0.825 },
  { id: "shen5", name: "", group: "白虎", x: 0.875, y: 0.825 },
  { id: "shen6", name: "", group: "白虎", x: 0.89, y: 0.825 },
  { id: "jing", name: "井宿", group: "朱雀", x: 0.2, y: 0.88, descYanming: "井宿主水衡，决断水利。春分日躔于此，故曰东井。", descLiqingning: "井宿一格一格的，像谁在天上凿了口井。" },
  { id: "jing1", name: "", group: "朱雀", x: 0.23, y: 0.88 },
  { id: "jing2", name: "", group: "朱雀", x: 0.2, y: 0.91 },
  { id: "jing3", name: "", group: "朱雀", x: 0.23, y: 0.91 },
  { id: "jing4", name: "", group: "朱雀", x: 0.2, y: 0.94 },
  { id: "jing5", name: "", group: "朱雀", x: 0.23, y: 0.94 },
  { id: "gui", name: "鬼宿", group: "朱雀", x: 0.3, y: 0.9, descYanming: "鬼宿又名舆鬼，主祠祀死丧。其中积尸气，望之幽幽。", descLiqingning: "鬼宿朦朦胧胧，像一盏没点亮的灯笼。" },
  { id: "gui1", name: "", group: "朱雀", x: 0.33, y: 0.9 },
  { id: "gui2", name: "", group: "朱雀", x: 0.33, y: 0.93 },
  { id: "gui3", name: "", group: "朱雀", x: 0.3, y: 0.93 },
  { id: "liu", name: "柳宿", group: "朱雀", x: 0.4, y: 0.88, descYanming: "柳宿为朱雀之喙，主草木厨膳。尝百草，先问它一味。", descLiqingning: "柳宿弯弯的，像雀鸟衔着一枝嫩柳。" },
  { id: "liu1", name: "", group: "朱雀", x: 0.43, y: 0.89 },
  { id: "liu2", name: "", group: "朱雀", x: 0.42, y: 0.91 },
  { id: "liu3", name: "", group: "朱雀", x: 0.44, y: 0.92 },
  { id: "liu4", name: "", group: "朱雀", x: 0.41, y: 0.94 },
  { id: "xing", name: "星宿", group: "朱雀", x: 0.5, y: 0.89, descYanming: "星宿为朱雀之颈，主衣裳文绣，亦主急兵。七星相连如项饰。", descLiqingning: "星宿排成一串，像雀颈上挂的七颗小铃。" },
  { id: "xing1", name: "", group: "朱雀", x: 0.52, y: 0.88 },
  { id: "xing2", name: "", group: "朱雀", x: 0.54, y: 0.9 },
  { id: "xing3", name: "", group: "朱雀", x: 0.51, y: 0.92 },
  { id: "xing4", name: "", group: "朱雀", x: 0.53, y: 0.93 },
  { id: "xing5", name: "", group: "朱雀", x: 0.55, y: 0.91 },
  { id: "zhang", name: "张宿", group: "朱雀", x: 0.6, y: 0.88, descYanming: "张宿为朱雀之嗉，主珍宝宴飨。嗉满则宴，嗉空则藏。", descLiqingning: "张宿圆圆的，像雀鸟鼓起的腮帮子。" },
  { id: "zhang1", name: "", group: "朱雀", x: 0.63, y: 0.89 },
  { id: "zhang2", name: "", group: "朱雀", x: 0.62, y: 0.91 },
  { id: "zhang3", name: "", group: "朱雀", x: 0.64, y: 0.92 },
  { id: "zhang4", name: "", group: "朱雀", x: 0.61, y: 0.94 },
  { id: "yi", name: "翼宿", group: "朱雀", x: 0.7, y: 0.88, descYanming: "翼宿主乐府俳倡，亦主远客。风起翼张，便有客自远方来。", descLiqingning: "翼宿舒舒的，像朱雀抖开两翼要飞。" },
  { id: "yi1", name: "", group: "朱雀", x: 0.72, y: 0.87 },
  { id: "yi2", name: "", group: "朱雀", x: 0.74, y: 0.89 },
  { id: "yi3", name: "", group: "朱雀", x: 0.71, y: 0.91 },
  { id: "yi4", name: "", group: "朱雀", x: 0.73, y: 0.92 },
  { id: "yi5", name: "", group: "朱雀", x: 0.75, y: 0.9 },
  { id: "yi6", name: "", group: "朱雀", x: 0.72, y: 0.94 },
  { id: "zhen", name: "轸宿", group: "朱雀", x: 0.8, y: 0.88, descYanming: "轸宿为朱雀之尾，主车骑风雨。古以轸主风，亦主冢宰之事。", descLiqingning: "轸宿长长拖在最后，像雀尾扫过一地星尘。" },
  { id: "zhen1", name: "", group: "朱雀", x: 0.82, y: 0.9 },
  { id: "zhen2", name: "", group: "朱雀", x: 0.79, y: 0.92 },
  { id: "zhen3", name: "", group: "朱雀", x: 0.81, y: 0.93 },
  { id: "ziwei", name: "紫微", group: "中宫", constel: "beidou", x: 0.46, y: 0.3, descYanming: "“三垣”是北天极附近的三个星区，被认为是“天上帝国”的核心所在。", descLiqingning: "紫微垣是三垣之中垣，传说是天帝居住的宫殿，又叫紫宫。位于北天极的中心。" },
  { id: "beiji", name: "北极", group: "中宫", constel: "beidou", x: 0.421, y: 0.28, descYanming: "北极星即紫微星，它恒定不动，众星环绕，被视为“帝星”，也被称为“天之枢”。", descLiqingning: "“为政以德，譬如北辰，居其所，而众星共（拱）之。”——《论语·为政》" },
  { id: "bd1", name: "天枢", group: "中宫", constel: "beidou", x: 0.5, y: 0.3, descYanming: "天枢是北斗第一星，也叫贪狼。", descLiqingning: "天枢悬阆中，斗柄运鸿蒙。" },
  { id: "bd2", name: "天璇", group: "中宫", constel: "beidou", x: 0.54, y: 0.31, descYanming: "天璇是北斗第二星，又称巨门。", descLiqingning: "玉屏横云阙，天璇入帝乡。" },
  { id: "bd3", name: "天玑", group: "中宫", constel: "beidou", x: 0.56, y: 0.35, descYanming: "天玑是北斗第三星，又叫禄存。", descLiqingning: "玉京群帝集北斗，或骑骐驎翳凤凰。" },
  { id: "bd4", name: "天权", group: "中宫", constel: "beidou", x: 0.52, y: 0.38, descYanming: "天权是北斗第四星，意为“天上的平衡”。", descLiqingning: "天权又名文曲，象征着文运。" },
  { id: "bd5", name: "玉衡", group: "中宫", constel: "beidou", x: 0.46, y: 0.39, descYanming: "玉衡是北斗第五星，也称廉贞。", descLiqingning: "“玉衡指孟冬，众星何历历。”古诗文常以玉衡代指北斗。" },
  { id: "bd6", name: "开阳", group: "中宫", constel: "beidou", x: 0.4, y: 0.4, descYanming: "开阳是北斗第六星，古名武曲。它身旁还有颗隐星，肉眼难辨。", descLiqingning: "武曲星掌管天下武运，维护天下太平。" },
  { id: "bd7", name: "摇光", group: "中宫", constel: "beidou", x: 0.34, y: 0.41, descYanming: "摇光是北斗第七星，也叫破军，是勺柄最末一颗。斗柄所指，定四时。", descLiqingning: "破军有先破后立之意。" },
  { id: "taiwei", name: "太微", group: "中宫", constel: "zhong", x: 0.58, y: 0.42, descYanming: "太微垣是三垣的“上垣”，象征着天帝和大臣们处理政务的朝廷。被称为“三光之廷。”", descLiqingning: "“太微，天子庭也，五帝之座也，十二诸侯府也。其外蕃，九卿也。”——《晋书·天文志》" },
  { id: "tianshi", name: "天市", group: "中宫", constel: "zhong", x: 0.44, y: 0.46, descYanming: "天市垣三垣的“下垣”，象征着平民百姓居住和进行贸易的繁华集市。", descLiqingning: "“天市，二十二星，主国市聚交易之所。”——《晋书·天文志》" },
  { id: "gouchen", name: "勾陈一", group: "中宫", constel: "zhong", x: 0.4, y: 0.34, descYanming: "勾陈一即北极星（小熊座α），是北天极附近最亮的恒星。", descLiqingning: "勾陈本是上古官名，掌天子禁卫；星空里它守在帝星之侧。" },
  { id: "dixing", name: "帝", group: "中宫", constel: "zhong", x: 0.49, y: 0.33, descYanming: "帝星即北极二，古称“太乙”，居紫微垣中，象征天帝之座。", descLiqingning: "“中宫天极星，其一明者，太一之常居也。”——《史记·天官书》" },
];

window.YLT_CFG.starLinks = [
  ["dou", "dou1"],
  ["dou1", "dou2"],
  ["dou2", "dou3"],
  ["dou3", "dou4"],
  ["dou4", "dou5"],
  ["niu", "niu1"],
  ["niu1", "niu2"],
  ["niu2", "niu3"],
  ["nv", "nv1"],
  ["nv1", "nv2"],
  ["nv2", "nv3"],
  ["xu", "xu1"],
  ["wei2", "wei21"],
  ["wei21", "wei22"],
  ["shi", "shi1"],
  ["bi", "bi1"],
  ["jiao", "jiao1"],
  ["kang", "kang1"],
  ["kang1", "kang2"],
  ["kang2", "kang3"],
  ["di", "di1"],
  ["di1", "di2"],
  ["di2", "di3"],
  ["fang", "fang1"],
  ["fang1", "fang2"],
  ["fang2", "fang3"],
  ["xin", "xin1"],
  ["xin1", "xin2"],
  ["wei", "wei1"],
  ["wei1", "wei2"],
  ["wei2", "wei3"],
  ["wei3", "wei4"],
  ["wei4", "wei5"],
  ["wei5", "wei6"],
  ["ji", "ji1"],
  ["ji1", "ji2"],
  ["ji2", "ji3"],
  ["kui", "kui1"],
  ["kui1", "kui2"],
  ["kui2", "kui3"],
  ["kui3", "kui4"],
  ["lou", "lou1"],
  ["lou1", "lou2"],
  ["wei3", "wei31"],
  ["wei31", "wei32"],
  ["mao", "mao1"],
  ["mao1", "mao2"],
  ["mao2", "mao3"],
  ["mao3", "mao4"],
  ["mao4", "mao5"],
  ["bi2", "bi21"],
  ["bi21", "bi22"],
  ["bi22", "bi23"],
  ["bi23", "bi24"],
  ["zi", "zi1"],
  ["zi1", "zi2"],
  ["shen", "shen1"],
  ["shen1", "shen2"],
  ["shen2", "shen3"],
  ["shen3", "shen4"],
  ["shen4", "shen5"],
  ["shen5", "shen6"],
  ["jing", "jing1"],
  ["jing1", "jing2"],
  ["jing2", "jing3"],
  ["jing3", "jing4"],
  ["jing4", "jing5"],
  ["gui", "gui1"],
  ["gui1", "gui2"],
  ["gui2", "gui3"],
  ["liu", "liu1"],
  ["liu1", "liu2"],
  ["liu2", "liu3"],
  ["liu3", "liu4"],
  ["xing", "xing1"],
  ["xing1", "xing2"],
  ["xing2", "xing3"],
  ["xing3", "xing4"],
  ["xing4", "xing5"],
  ["zhang", "zhang1"],
  ["zhang1", "zhang2"],
  ["zhang2", "zhang3"],
  ["zhang3", "zhang4"],
  ["yi", "yi1"],
  ["yi1", "yi2"],
  ["yi2", "yi3"],
  ["yi3", "yi4"],
  ["yi4", "yi5"],
  ["yi5", "yi6"],
  ["zhen", "zhen1"],
  ["zhen1", "zhen2"],
  ["zhen2", "zhen3"],
  ["bd1", "bd2"],
  ["bd2", "bd3"],
  ["bd3", "bd4"],
  ["bd4", "bd5"],
  ["bd5", "bd6"],
  ["bd6", "bd7"],
  ["ziwei", "beiji"],
  ["beiji", "gouchen"],
  ["ziwei", "dixing"],
  ["taiwei", "tianshi"],
  ["gouchen", "taiwei"],
  ["dou", "niu"],
  ["niu", "nv"],
  ["nv", "xu"],
  ["xu", "wei2"],
  ["wei2", "shi"],
  ["shi", "bi"],
  ["jiao", "kang"],
  ["kang", "di"],
  ["di", "fang"],
  ["fang", "xin"],
  ["xin", "wei"],
  ["wei", "ji"],
  ["kui", "lou"],
  ["lou", "wei3"],
  ["wei3", "mao"],
  ["mao", "bi2"],
  ["bi2", "zi"],
  ["zi", "shen"],
  ["jing", "gui"],
  ["gui", "liu"],
  ["liu", "xing"],
  ["xing", "zhang"],
  ["zhang", "yi"],
  ["yi", "zhen"],
];
